version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "3004:3004"
    container_name: music-backend

  frontend:
    build:
      context: ./app-music2
      args:
        VITE_API_URL: https://apimusicapp.jacm.pro
    ports:
      - "5174:5174"
    depends_on:
      - backend
    container_name: music-frontend
